file_format: "1"
id: cornedong
name: Cornedong
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - cornedong_left
  - cornedong_right
  - cornedong_dongle